# General Jekyll Config
url: http://ctruman.info
highlighter: rouge
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: kramdown

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#15A4D4'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: jstart
    twitter: iAmChrisTruman
    hacker_news: ctruman
    google: 117181854404823173101
    linkedin: christophertruman

  # "Hi, I'm _______"
  name: Chris Truman
  email: cleetruman@gmail.com
  tagline: "iOS Developer in LA"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-36352828-2

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false 
